---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "serverless-filerunner.name" . }}-cm
data:
  Jenkinsfile: |-
    pipeline {
        agent any
        stages {
            stage('Tests') {
                steps {
                    echo "Hello World $BUILD_NUMBER"
                }
            }
        }
    }
